### ISSUE TITLE
Immediate parameterless function invocation  

### ISSUE THREAD

**Issue by eleventigers** [pakoito/RxMemoization#1]
It is not specified that the `func0` parameter will be invoked immediately after calling the parameterless function memoization method: https://github.com/pakoito/RxMemoization/blob/59e8366a7a57fa4cb4ee5c07354f9c8a205e4a9d/rxmemoization/src/main/java/com/pacoworks/rxmemoization/RxMemoization.java#L55. 
Wouldn't be more correct/beneficial to the library user if the original wrapped `func0` is invoked only when necessary?

**Comment by pakoito** [comment]
Good catch, let me fix it.

**Comment by pakoito** [comment]
Fixed by: https://github.com/pakoito/RxMemoization/commit/c327300d06eb39ccd4e3756d6f94cb3e6f1c2b57
